name: Release builder

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  tag-push-release:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Auto bump version
        id: auto_bump
        uses: kaskar2008/action-auto-bump-version@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: .github/release-configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.auto_bump.outputs.tag }}
          release_name: ${{ steps.auto_bump.outputs.tag }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
